### ISSUE TITLE
Not using heroku?

### ISSUE THREAD

**Issue by z3t0** [lstoll/gh2focus#2]
Sorry if this is a silly question, but how do I use this on my own linux server? Do I install heroku or?

**Comment by lstoll** [comment]
Hello, there's nothing really heroku specific about this, it's just the hosting service I chose to run it on (https://www.heroku.com/ - disclaimer, I work there these days) It's essentially a little ruby script. A few pointers for running it on a linux server:

* You will need a postgres database set up and created, as well as recent ruby and bundler installed
* You should probably run this as cron using the scheduler. Maybe make a script that does something like
```
GITHUB_USER=xxx GITHUB_TOKEN=xx MAILDROP_ADDRESS=xxx FROM_ADDRESS=xxx DATABASE_URL=postgres://user@server:port/databasename bundle exec issues2mail.rb
```
You can run that directly to get things working, then create a script with it and call it from cron however best works for you.

Hope this helps!
